development: &schedules
  schedule_due_reminders:
    class: ScheduleDueRemindersJob
    schedule: every minute
  schedule_due_daily_digests:
    class: ScheduleDueDailyDigestsJob
    schedule: every minute

production:
  <<: *schedules
